### ISSUE TITLE
Ajouter des valeurs dans la liste des types de lieux

### ISSUE THREAD

**Issue by xavier-calland** [GIP-GRADeS-BFC/SORMAS-Project#3]
Les types de lieux ne sont pas configurables et il apparait que cette liste est de type enum `TypeOfPlace` dans le code.

Il faudrait modifier cette liste pour proposer :

* Domicile _existant HOME/Domicile_
* Milieu familial élargi
* Evènement public ou privé _existant FESTIVITIES/Fêtes → libellé à modifier_
* Crèches
* Milieu scolaire et universitaire
* Etablissement d’hébergement de personnes âgées dépendantes (EHPAD)
* EMS de personnes handicapées
* Etablissements de santé _existant HOSPITAL/Hôpitaux  → libellé à modifier_
* Etablissements sociaux d’hébergement et d’insertion
* Communautés particulières
* Structures de soins résidentiels des personnes sans domicile fixe
* Etablissement pénitentiaires
* Milieux professionnels
* Moyens de transport _existant MEANS_OF_TRANSPORT/Moyens de transport_
* Autre _existant OTHER/Autre_
* Lieu public _PUBLIC_PLACE/Lieu public_
* Inconnu _existant UNKNOWN/Inconnu_

**Comment by OlivierLeuci** [comment]
@xavier-calland : Il semble que nous n'ayons que 9 type de lieux dans la liste

**Comment by OlivierLeuci** [comment]
@xavier-calland: oups, non c'est bon par contre l'ascenseur du composant n'est pas super intuitif...

**Comment by xavier-calland** [comment]
@OlivierLeuci On peut augmenter le nombre d'éléments affichés dans cette liste déroulante.
Si tu peux qu'on fasse le modif, je dirais en terme de workflow qu'il faut ouvrir une issue correspondant à cette modification. Ca permettra d'avoir une suivi sur cette demande (on fait ou pas, est-ce qu'il a des questions, dans quelle version c'est planifié, etc).
Ca te va comme fonctionnement ?

**Comment by OlivierLeuci** [comment]
Oui ça va, j'avais un pb sur mon poste. On laisse comme ça et on voit avec l'équipe fonctionnelle. Merci

**Comment by OlivierLeuci** [comment]
@xavier-calland : Après un retour sur ce dev, les users auraient voulu avoir un tri alphabétique sur la liste des lieux. Est-ce possible de faire une modif de code dans une branche et de refaire un pull request? Merci

**Comment by xavier-calland** [comment]
Il n'y a de mécanisme de tri prévu dans l'application pour gérer les listes basées sur des enums.
La solution serait de modifier l'ordre des valeurs déclarées dans l'enums. Ces valeurs étant des clés d'identification (et non les libellés de traduction), cet ordre (dans l'enum) sera à revoir si les libellés viennent à changer.

**Comment by OlivierLeuci** [comment]
Décision de faire un nouveau ticket lié à ce dernier pour gérer l'évolution de la demande pour le tri.
