### ISSUE TITLE
Bouton "effacer" dans la fiche d'une action définie dans le cadre d'un évènement

### ISSUE THREAD

**Issue by carolinverset** [GIP-GRADeS-BFC/SORMAS-Project#33]
### Bug Description

Le bouton "Effacer" ne fonctionne pas et renvoie un message d'erreur

**Comment by xavier-calland** [comment]
Peux-tu m'indiquer le profil de l'utilisateur avec lequel le problème se produit ?

**Comment by xavier-calland** [comment]
@GRADeS-Gwen Tu peux fournir le fichier server.log ?

**Comment by GRADeS-Gwen** [comment]
voici 
[server.log](https://github.com/GIP-GRADeS-BFC/SORMAS-Project/files/4885048/server.log)

**Comment by carolinverset** [comment]
@xavier-calland 
J'ai le profil admin mais après avoir retesté, je vois que ça fonctionne désormais. 
Super !

**Comment by xavier-calland** [comment]
OK
