### ISSUE TITLE
Module de suivi des actions sur un événement

### ISSUE THREAD

**Issue by xavier-calland** [GIP-GRADeS-BFC/SORMAS-Project#5]
Ajouter la notion d'actions sur les événements.

# Définition d'une action

Une action est composée des informations suivantes :
* contexte
  * pour le moment seul le contexte "événement" est géré
  * `actioncontext`
  * type enum (EVENT) 
  * obligatoire
  * libellé : "Contexte"
* événement
  * `event_id`
  * type id (bigint)
  * obligatoire
  * libellé : "Événement"
* priorité
  * `priority`
  * type enum (HIGH, NORMAL, LOW) / (basse, normale, haute)
  * facultatif
  * libellé : "Priorité"
* date
  * `date`
  * type date
  * obligatoire, pas de date dans le future
  * libellé : "Date"
* statut
  * `actionstatus`
  * type enum (PENDING, IN_PROGRESS, DONE) / (terminée, en cours, à faire)
  * obligatoire, pas de date dans le future
  * libellé : "Statut"
* date de modification du statut
  * `statuschangedate`
  * type date
  * géré automatiquement, non visible dans le formulaire
* utilisateur ayant créé l'action
  * `creatoruser_id`
  * type id (bigint)
  * géré automatiquement, non visible dans le formulaire de saisie
* description
  * `description`
  * type texte riche
  * facultatif
  * libellé : "Description"
* réponse de la 
  * `reply`
  * type texte riche
  * facultatif, non visible à la création d'une action
  * libellé : "Réponse"

Champs techniques pour historisation et traçabilité
* `changedate timestamp not null`
* `creationdate timestamp not null`
* `sys_period tstzrange not null`

# Création / modification d'une action

Le formulaire propose les champs décrits ci-dessus avec les particularités suivates :
* À la création, le champ "réponse" n'est pas visible.
Il ne sera visible qu'en modification d'une action existante
* En modification d'une action existante, le champs "description" n'est modifiable que par l'utilisateur ayant créé l'action

Les mécanismes d'historisation et traçabilité (base audit + table `*_histo`) sont activés sur les actions.

# Onglet de liste des actions

L’ensemble des actions saisies autour d’un évènement par les utilisateurs est récapitulé dans un onglet particulier "Suivi des actions". Un bouton permettant de créer une nouvelle action est également visible.

Pour chaque action, les champs suivants apparaissent :

* Date
* Créateur de l'action
* Statut
* Priorité
* Descriptif / réponse

Les actions sont affichées triées sur le champ "date" de façon décroissante.

Une liste déroulante permet de filtrer les actions en fonction de leur statut.

Un bouton permet de modifier l'action.

# Récapitulatif sur la fiche d'un événement

La fiche de détail d'un événement affiche dans la colonne de droite (en dessous des tâches) un cadre avec :
* un bouton permettant de créer un nouvelle action pour l'événement (affiche la popin avec le formulaire de création)
* le nombre d'actions pour chaque statut

# Droits utilisateurs

La gestion des droits utilisateurs pour la création et modification des actions sur les événements sera calquées sur ce qui est en place pour la gestion des participants à un événement.

**Comment by carolinverset** [comment]
@xavier-calland 
Suite à la démo de tes développements en GT, voici la liste des ajustements qui seraient à entreprendre : 

- changer le nom de l'onglet "Actions de l'évènement" en "Suivi de l'évènement"
- vérifier le fonctionnement du bouton effacer dans le composant éditeur d'une action
- Ajouter l'information sur le nom de la dernière personne ayant modifié l'action (en complément du nom de la personne ayant créée l'action)

Possible pour tu d'intégrer ces ajustements ? Sous quel délais ? 
merci bcp !

**Comment by xavier-calland** [comment]
@carolinverset Les modifications sont proposées en PR #37 et #38
