### ISSUE TITLE
Dupliquer la fonctionnalité "suivi des contacts" pour les cas 

### ISSUE THREAD

**Issue by xavier-calland** [GIP-GRADeS-BFC/SORMAS-Project#6]
## Statut du suivi

* Ajouter les champs suivant dans "cas" (`cases` et `cases_history`)
```
followupstatus varchar(255);
followupcomment varchar(512);
followupuntil timestamp;
overwritefollowupuntil boolean;
```
* Intégrer dans le formulaire de modification d'un cas `CaseDataForm`
* Ajouter un filtre sur le statut du suivi dans la liste des cas
* Reprendre les libellés utilisés dans le suivi des contacts

## Visites sur les cas

* Ajouter une table `cases_visits` (avec classes java nécessaires)
* Utiliser les droits existant pour les visites des contacts (`VISIT_*`)
* Ajouter l'onglet "Visites de suivi" dans la page de détail d'un cas (même comportement que la liste d
  * colonnes : Date et heure de visite, Personne disponible et coopérative ?, Commentaires de visite, Maladie, Symptomatic, Temperature
  * tri
  * pas de filtre
  * actions de groupe : suppression
* Popup de modification

### Règles de mises à jour

Actuellement, la mise à jour d'un contact ou d'un visite va entraîner 2 traitements :

* Rattachement des contacts à des visites
Recherche des visites correspondant au contact (même personne, maladie et date) pour ajouter le lien entre ce contact et la visite.
Faut-il intégrer ce mécanisme pour les cas ? _Cela me semble un comportement de l'application à reprendre dans les cas pour garde de la cohérence entre les données_
_→ Une visite pourra être lié à la fois à un contact et un cas (dans le cas où une personne est à la fois cas et contact)_

* Mise à jour du statut du suivi et de la date "suivi jusqu'à" 

> Tous les contacts avec la personne et la maladie spécifiées dont la dernière date de contact ou la date du rapport (selon la disponibilité) est antérieure à la date de référence et, si disponible, dont le suivi jusqu'à la date est postérieure à la date de référence , y compris un décalage pour permettre une certaine tolérance.

> Si la dernière visite n'a pas été coopérative et a eu lieu à la dernière date de recherche des contacts, nous devons effectuer une visite supplémentaire
> Si la dernière visite a été coopérative et a eu lieu à la dernière date de recherche des contacts, revenir au suivi jusqu'à la date d'origine

Faut-il intégrer ce mécanisme pour les cas ? _Cela me semble un comportement de l'application à reprendre dans les cas pour garde de la cohérence entre les données_

**→ On reprend les mécanismes existants pour les contacts**

### Page de suivi des visites global à tous les cas

Il y a-t-il besoin de la page "Suivi des visites" en mode tableau croisé pour les cas ? (comme pour les [contacts](https://sormas.test.esante-bfc.fr/sormas-ui/#!contacts/?reportDateTo=1593035999999&followUpUntilFrom=1591826400000&dateFilterOption=DATE))
1 ligne par cas avec les jours en colonnes et des couleurs pour les statuts des visites

**→ Oui**

### Liste "Répertoire de cas"

* Mode basique
Faut-il ajouter les colonnes suivantes dans le tableau ?
  * Statut du suivi
  * Suivi jusqu’à (dd/MM/yyyy)
  * Nombre de visites

**→ Oui**

### Exports

Quels besoins pour les exports, quels exports doivent être modifiés et/ou ajoutés ?

* Depuis la liste des visites pour un cas : **OK**
* Depuis le liste des cas
  * Export des cas - basique : cela exporte les colonnes présentes dans la liste "Répertoire de cas" **OK**
  * Export des cas - détaillé : ajouter les champs suivants ? (c'est ce qu'il y a pour les contacts) **OK**
    * Statut du suivi
    * Suivi jusqu’à (dd/MM/yyyy)
    * Nombre de visites
    * Symptomatique lors de la dernière visite coopérative?
    * Date de la dernière visite coopérative (dd/MM/yyyy)
    * Symptômes lors de la dernière visite coopérative
  * Créer un "Export du suivi" (comme dans les contacts) ? **pas pour le moment**

**Comment by OlivierLeuci** [comment]
@xavier-calland et @jlv-atolcd : Xavier, L'équipe fonctionnelle n'est pas tout le temps sur le Github. Du coup, des questions sont passées inaperçues. Pourrait-on prévoir des petits points de situation en visio pour faire le tour de vos questions et y apporter les réponses? Qu'en penses-tu?

**Comment by xavier-calland** [comment]
@OlivierLeuci C'est effectivement l'idée. J'attendais d'avoir fait le tour du ticket (de ce qu'il implique) pour avoir toutes les questions à poser.
Je devrais avoir terminé d'ici demain. On peut caler une visio pour organiser cet échange.
